version: "3.7"
services:
  mongo:
    image: mongo:latest
    volumes:
      - ../mongodb/data:/data
    ports:
      - 27018:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongouser
      - MONGO_INITDB_ROOT_PASSWORD=mongopassword
      - MONGO_INITDB_DATABASE=miniserver